version: '3.8'
services:
  ms_stats_python:
    build: ./ms_stats
    ports:
      - "7200:8000"
  ms_resend_nodets:
    build: ./ms_resend
    ports:
      - "3000:3000"
    volumes:
      - ./ms_resend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 35001:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql

  facturascripts:
    image: facturascripts/facturascripts:latest
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./ms_facturascripts1:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
