<?php
define('FS_COOKIES_EXPIRE', 31536000);
define('FS_ROUTE', '');
define('FS_DB_FOREIGN_KEYS', true);
define('FS_DB_TYPE_CHECK', true);
define('FS_MYSQL_CHARSET', 'utf8');
define('FS_MYSQL_COLLATE', 'utf8_bin');
define('FS_LANG', 'es_ES');
define('FS_TIMEZONE', 'Europe/Budapest');
define('FS_DB_TYPE', 'mysql');
define('FS_DB_HOST', 'mysql');
define('FS_DB_PORT', '3306');
define('FS_DB_NAME', 'facturascripts');
define('FS_DB_USER', 'root');
define('FS_DB_PASS', 'clavedemysql2024');
define('FS_HIDDEN_PLUGINS', '');
define('FS_DEBUG', false);
define('FS_DISABLE_ADD_PLUGINS', false);
define('FS_DISABLE_RM_PLUGINS', false);